repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: check-yaml
        - id: end-of-file-fixer
          exclude: "_test_data"
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.1
      hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.16
      hooks:
      - id: mdformat
        exclude: "_test_data"
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
