repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: check-yaml
        - id: end-of-file-fixer
          exclude: "_test_data"
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
        - id: black
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: 'v0.0.260'
      hooks:
        - id: ruff
          args: ["--fix"]
          exclude: test/sphinx_ext_test_data/example.py
    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.16
      hooks:
      - id: mdformat
        exclude: "_test_data"
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.1.1"
      hooks:
        - id: mypy
          exclude: "test"
          args: ["--strict"]
          additional_dependencies:
            - types-docutils
            - sphinx
            - types-markdown
            - mkdocs
            - pymdown-extensions
